#!/bin/sh
# Copyright (C) 2010,2011,2014 The ESPResSo project
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.
#
if test -n "$PYTHONPATH"; then
    PYTHONPATH=$PYTHONPATH:/home/alexander/mygit/UP/Esp/espresso-3.3.1/es-build
else
    PYTHONPATH=/home/alexander/mygit/UP/Esp/espresso-3.3.1/es-build
fi
export PYTHONPATH
exec /usr/bin/python $@
